version: "3.6"
services:
  client:
    container_name: client
    build: ./client
    env_file: ./client/.env
    environment:
    - CLIENT_PORT=${CLIENT_PORT}
    expose:
      - ${CLIENT_PORT}
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    volumes: 
      - ./client:/client
      - node_modules_c:/client/node_modules
        
volumes: 
  node_modules_c:
      